package engine

import (
	"encoding/json"
	"time"

	"github.com/varavelio/rienda/internal/llm"
	"github.com/varavelio/rienda/internal/session"
	"github.com/varavelio/rienda/internal/tokens"
	"github.com/varavelio/rienda/internal/tool"
)

// EventType discriminates the payload carried by an Event.
type EventType string

const (
	// EventRunStart opens a run with the session, agent and model identifiers,
	// the entry of the user message that started it and the diagnostics of the
	// workspace. It is the only event that reports a diagnostic, which is what
	// makes a diagnostic a per-run report.
	EventRunStart EventType = "run_start"
	// EventTextDelta carries an incremental text fragment in Text.
	EventTextDelta EventType = "text_delta"
	// EventThinkingDelta carries an incremental reasoning fragment in Text.
	EventThinkingDelta EventType = "thinking_delta"
	// EventToolCall announces a tool invocation that is about to run.
	EventToolCall EventType = "tool_call"
	// EventToolOutput carries one chunk of tool output in Stream and Output.
	EventToolOutput EventType = "tool_output"
	// EventToolResult closes a tool invocation with its model-facing result.
	EventToolResult EventType = "tool_result"
	// EventMessageEnd closes an assistant message after it is persisted.
	EventMessageEnd EventType = "message_end"
	// EventRetry reports that a model call failed with a transient error and
	// is being retried after a backoff. Discard reports that the failed
	// attempt streamed output the consumer must drop.
	EventRetry EventType = "retry"
	// EventCompactionStart opens a compaction of the conversation.
	EventCompactionStart EventType = "compaction_start"
	// EventCompactionEnd closes a compaction with the persisted checkpoint and
	// the measurements around it.
	EventCompactionEnd EventType = "compaction_end"
	// EventContext reports the estimated context of the request the next turn
	// would send. The engine emits it after every change to the stored
	// conversation — the prompt of the run, an assistant message, the results
	// of a tool batch and a checkpoint — so a front end shows a live context
	// figure while a run is in flight instead of only when it ends.
	EventContext EventType = "context"
	// EventRunEnd closes a run. It is the last event of every channel.
	EventRunEnd EventType = "run_end"
	// EventError reports the failure that ended a run.
	EventError EventType = "error"
)

// EndReason explains why a run ended.
type EndReason string

const (
	// EndReasonTurn marks a run the model finished without requesting tools.
	EndReasonTurn EndReason = "end_turn"
	// EndReasonInterrupted marks a run stopped by context cancellation.
	EndReasonInterrupted EndReason = "interrupted"
	// EndReasonError marks a run stopped by a failure.
	EndReasonError EndReason = "error"
)

// Usage reports the token consumption of an assistant message.
type Usage struct {
	// InputTokens is the number of tokens in the request input.
	InputTokens int `json:"inputTokens,omitempty"`

	// OutputTokens is the number of tokens generated by the model.
	OutputTokens int `json:"outputTokens,omitempty"`

	// ReasoningTokens is the subset of OutputTokens spent on reasoning.
	ReasoningTokens int `json:"reasoningTokens,omitempty"`

	// CacheReadTokens is the number of input tokens served from the provider
	// prompt cache.
	CacheReadTokens int `json:"cacheReadTokens,omitempty"`

	// CacheWriteTokens is the number of input tokens written to the provider
	// prompt cache.
	CacheWriteTokens int `json:"cacheWriteTokens,omitempty"`
}

// usageFrom projects provider usage into event usage, nil when the provider
// reported nothing.
func usageFrom(usage llm.Usage) *Usage {
	if usage == (llm.Usage{}) {
		return nil
	}
	return &Usage{
		InputTokens:      usage.InputTokens,
		OutputTokens:     usage.OutputTokens,
		ReasoningTokens:  usage.ReasoningTokens,
		CacheReadTokens:  usage.CacheReadTokens,
		CacheWriteTokens: usage.CacheWriteTokens,
	}
}

// CompactionInfo describes a finished compaction to a front end: the
// checkpoint that was persisted and the measurements on either side of it.
type CompactionInfo struct {
	// Entry is the persisted checkpoint.
	Entry session.Entry `json:"entry"`

	// TokensBefore is the size of the summarized range, measured by the
	// procedure.
	TokensBefore int `json:"tokensBefore"`

	// TokensAfter is the size of the request the next turn would send once the
	// checkpoint is in place, measured by the engine.
	TokensAfter int `json:"tokensAfter"`

	// Usage reports the token consumption of the summarization call.
	Usage *Usage `json:"usage,omitempty"`
}

// ContextInfo reports how much of the context window of a model the request the
// next turn would send consumes. It is what an EventContext carries, so a front
// end renders the live figure of a run without measuring anything itself.
type ContextInfo struct {
	// Used is the estimated number of tokens the request consumes.
	Used int `json:"used"`

	// Window is the context window of the model the request is measured
	// against.
	Window int `json:"window"`

	// Percent is the share of the window in use, between 0 and 100, rounded to
	// one decimal.
	Percent float64 `json:"percent"`
}

// contextFrom projects a context measurement into event form.
func contextFrom(report tokens.Report) *ContextInfo {
	return &ContextInfo{Used: report.Used, Window: report.Window, Percent: report.Percent}
}

// Event is a single update emitted while a run is in flight. Only the fields
// valid for the event Type carry meaning; the rest stay at their zero value.
//
// The struct is flat and serializable, so the same events can feed a terminal
// UI, a protocol server or a test.
type Event struct {
	// Type selects which fields of the event carry meaning.
	Type EventType `json:"type"`

	// SessionID, AgentID and ModelID identify the run in EventRunStart.
	SessionID string `json:"sessionId,omitempty"`
	AgentID   string `json:"agentId,omitempty"`
	ModelID   string `json:"modelId,omitempty"`

	// EntryID identifies the persisted entry an event refers to: the user
	// message in EventRunStart and the assistant message in EventMessageEnd.
	EntryID string `json:"entryId,omitempty"`

	// Diagnostics lists the non-fatal problems found while discovering the
	// skills of the workspace, one entry per skill, identified by the relative
	// path of its SKILL.md. It is only meaningful in EventRunStart, which
	// already opens a run exactly once: the diagnostics are therefore reported
	// once per run, never by a context measurement and never by a compaction,
	// and nothing has to remember that they were reported.
	Diagnostics []string `json:"diagnostics,omitempty"`

	// Text carries incremental text in EventTextDelta, incremental reasoning
	// in EventThinkingDelta and the result text in EventToolResult.
	Text string `json:"text,omitempty"`

	// ToolCallID, ToolName and Arguments identify the invocation in
	// EventToolCall, EventToolOutput and EventToolResult.
	ToolCallID string          `json:"toolCallId,omitempty"`
	ToolName   string          `json:"toolName,omitempty"`
	Arguments  json.RawMessage `json:"arguments,omitempty"`

	// Stream and Output carry one output chunk in EventToolOutput.
	Stream tool.Stream `json:"stream,omitempty"`
	Output string      `json:"output,omitempty"`

	// IsError marks the failed invocation of an EventToolResult.
	IsError bool `json:"isError,omitempty"`

	// StopReason and Usage describe the persisted assistant message in
	// EventMessageEnd.
	StopReason llm.StopReason `json:"stopReason,omitempty"`
	Usage      *Usage         `json:"usage,omitempty"`

	// Attempt and RetryIn describe the retry of an EventRetry: the 1-based
	// number of the attempt that failed and the wait before the next one.
	Attempt int           `json:"attempt,omitempty"`
	RetryIn time.Duration `json:"retryIn,omitempty"`

	// Discard reports, in an EventRetry, that the failed attempt already
	// streamed output, which the consumer must drop before the retried
	// response replaces it.
	Discard bool `json:"discard,omitempty"`

	// Compaction carries the checkpoint of an EventCompactionEnd: the entry
	// that was persisted, what the summarized range measured and what the
	// request measured once the checkpoint was in place. It describes nothing
	// about why the compaction happened, because a front end only renders the
	// checkpoint.
	Compaction *CompactionInfo `json:"compaction,omitempty"`

	// Context carries the measurement of an EventContext: the estimated size
	// of the request the next turn would send and the context window it is
	// measured against.
	Context *ContextInfo `json:"context,omitempty"`

	// Reason explains why the run ended in EventRunEnd.
	Reason EndReason `json:"reason,omitempty"`

	// Error carries the failure description of an EventRetry and of an
	// EventError.
	Error string `json:"error,omitempty"`
}
