package engine

import (
	"encoding/json"
	"time"

	"github.com/varavelio/rienda/internal/llm"
	"github.com/varavelio/rienda/internal/tool"
)

// EventType discriminates the payload carried by an Event.
type EventType string

const (
	// EventRunStart opens a run with the session, agent and model identifiers
	// and the entry of the user message that started it.
	EventRunStart EventType = "run_start"
	// EventTextDelta carries an incremental text fragment in Text.
	EventTextDelta EventType = "text_delta"
	// EventThinkingDelta carries an incremental reasoning fragment in Text.
	EventThinkingDelta EventType = "thinking_delta"
	// EventToolCall announces a tool invocation that is about to run.
	EventToolCall EventType = "tool_call"
	// EventToolOutput carries one chunk of tool output in Stream and Output.
	EventToolOutput EventType = "tool_output"
	// EventToolResult closes a tool invocation with its model-facing result.
	EventToolResult EventType = "tool_result"
	// EventMessageEnd closes an assistant message after it is persisted.
	EventMessageEnd EventType = "message_end"
	// EventRetry reports that a model call failed with a transient error and
	// is being retried after a backoff. Discard reports that the failed
	// attempt streamed output the consumer must drop.
	EventRetry EventType = "retry"
	// EventRunEnd closes a run. It is the last event of every channel.
	EventRunEnd EventType = "run_end"
	// EventError reports the failure that ended a run.
	EventError EventType = "error"
)

// EndReason explains why a run ended.
type EndReason string

const (
	// EndReasonTurn marks a run the model finished without requesting tools.
	EndReasonTurn EndReason = "end_turn"
	// EndReasonInterrupted marks a run stopped by context cancellation.
	EndReasonInterrupted EndReason = "interrupted"
	// EndReasonError marks a run stopped by a failure.
	EndReasonError EndReason = "error"
)

// Usage reports the token consumption of an assistant message.
type Usage struct {
	// InputTokens is the number of tokens in the request input.
	InputTokens int `json:"inputTokens,omitempty"`

	// OutputTokens is the number of tokens generated by the model.
	OutputTokens int `json:"outputTokens,omitempty"`

	// ReasoningTokens is the subset of OutputTokens spent on reasoning.
	ReasoningTokens int `json:"reasoningTokens,omitempty"`

	// CacheReadTokens is the number of input tokens served from the provider
	// prompt cache.
	CacheReadTokens int `json:"cacheReadTokens,omitempty"`

	// CacheWriteTokens is the number of input tokens written to the provider
	// prompt cache.
	CacheWriteTokens int `json:"cacheWriteTokens,omitempty"`
}

// usageFrom projects provider usage into event usage, nil when the provider
// reported nothing.
func usageFrom(usage llm.Usage) *Usage {
	if usage == (llm.Usage{}) {
		return nil
	}
	return &Usage{
		InputTokens:      usage.InputTokens,
		OutputTokens:     usage.OutputTokens,
		ReasoningTokens:  usage.ReasoningTokens,
		CacheReadTokens:  usage.CacheReadTokens,
		CacheWriteTokens: usage.CacheWriteTokens,
	}
}

// Event is a single update emitted while a run is in flight. Only the fields
// valid for the event Type carry meaning; the rest stay at their zero value.
//
// The struct is flat and serializable, so the same events can feed a terminal
// UI, a protocol server or a test.
type Event struct {
	// Type selects which fields of the event carry meaning.
	Type EventType `json:"type"`

	// SessionID, AgentID and ModelID identify the run in EventRunStart.
	SessionID string `json:"sessionId,omitempty"`
	AgentID   string `json:"agentId,omitempty"`
	ModelID   string `json:"modelId,omitempty"`

	// EntryID identifies the persisted entry an event refers to: the user
	// message in EventRunStart and the assistant message in EventMessageEnd.
	EntryID string `json:"entryId,omitempty"`

	// Text carries incremental text in EventTextDelta, incremental reasoning
	// in EventThinkingDelta and the result text in EventToolResult.
	Text string `json:"text,omitempty"`

	// ToolCallID, ToolName and Arguments identify the invocation in
	// EventToolCall, EventToolOutput and EventToolResult.
	ToolCallID string          `json:"toolCallId,omitempty"`
	ToolName   string          `json:"toolName,omitempty"`
	Arguments  json.RawMessage `json:"arguments,omitempty"`

	// Stream and Output carry one output chunk in EventToolOutput.
	Stream tool.Stream `json:"stream,omitempty"`
	Output string      `json:"output,omitempty"`

	// IsError marks the failed invocation of an EventToolResult.
	IsError bool `json:"isError,omitempty"`

	// StopReason and Usage describe the persisted assistant message in
	// EventMessageEnd.
	StopReason llm.StopReason `json:"stopReason,omitempty"`
	Usage      *Usage         `json:"usage,omitempty"`

	// Attempt and RetryIn describe the retry of an EventRetry: the 1-based
	// number of the attempt that failed and the wait before the next one.
	Attempt int           `json:"attempt,omitempty"`
	RetryIn time.Duration `json:"retryIn,omitempty"`

	// Discard reports, in an EventRetry, that the failed attempt already
	// streamed output, which the consumer must drop before the retried
	// response replaces it.
	Discard bool `json:"discard,omitempty"`

	// Reason explains why the run ended in EventRunEnd.
	Reason EndReason `json:"reason,omitempty"`

	// Error carries the failure description of an EventRetry and of an
	// EventError.
	Error string `json:"error,omitempty"`
}
