//go:build e2e

package harness

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"slices"
	"strings"
	"sync"
	"testing"
	"time"
)

// arrivalTimeout bounds how long a test waits for the fake provider to receive
// a request before it fails instead of hanging the suite.
const arrivalTimeout = 10 * time.Second

// Token counts the fake provider reports for the responses built with Text and
// ToolCall, so tests can assert the usage that reaches a session file.
const (
	// DefaultInputTokens is the reported number of input tokens.
	DefaultInputTokens = 42
	// DefaultOutputTokens is the reported number of output tokens.
	DefaultOutputTokens = 7
)

// wireAssistant is the assistant role shared by the codecs of the protocols.
const wireAssistant = "assistant"

// Turn describes one model response of a script: the reasoning and the text
// the model produces, the tool calls it requests, and the token consumption it
// reports.
type Turn struct {
	// Text is the answer text of the response.
	Text string

	// Thinking is the reasoning the model produces before its answer.
	Thinking string

	// Calls lists the tool invocations the model requests, in order.
	Calls []Call

	// Usage is the token consumption of the response. A nil value makes the
	// response report none.
	Usage *Usage

	// Chunks splits the streamed text and arguments into that many fragments,
	// which exercises incremental delivery. It defaults to one fragment.
	Chunks int

	// ChunkDelay delays every streamed fragment, keeping a response in flight
	// for the tests that act while the binary is working.
	ChunkDelay time.Duration

	// Status makes the provider answer the turn with that HTTP status and a
	// JSON error body instead of streaming a response, which lets a test
	// script a provider failure.
	Status int

	// Truncate drops the terminal events that close the response, so the
	// stream ends in the middle of its payloads, as a connection dropped
	// while the model was still answering. The text and the tool calls of the
	// turn are still streamed before the cut.
	Truncate bool
}

// Call describes one tool invocation requested by a model response.
type Call struct {
	// Name is the name of the invoked tool.
	Name string

	// Arguments is the argument object of the invocation, encoded as JSON.
	Arguments map[string]any

	// RawArguments replaces Arguments with a raw JSON payload, which lets
	// tests exercise the malformed arguments a model sometimes emits.
	RawArguments string

	// ID is the provider identifier of the call. It defaults to a unique
	// generated identifier.
	ID string
}

// Usage describes the token consumption reported by one model response.
type Usage struct {
	// InputTokens is the number of tokens in the request input.
	InputTokens int

	// OutputTokens is the number of tokens generated by the model.
	OutputTokens int

	// ReasoningTokens is the subset of OutputTokens spent on reasoning.
	ReasoningTokens int

	// CacheReadTokens is the number of input tokens served from the cache.
	CacheReadTokens int
}

// defaultUsage returns the token consumption of the responses built with the
// Text and ToolCall helpers.
func defaultUsage() *Usage {
	return &Usage{InputTokens: DefaultInputTokens, OutputTokens: DefaultOutputTokens}
}

// Text returns a turn that answers with the given text and reports the default
// token usage.
func Text(text string) Turn {
	return Turn{Text: text, Usage: defaultUsage()}
}

// ToolCall returns a turn that requests a single tool invocation and reports
// the default token usage.
func ToolCall(name string, arguments map[string]any) Turn {
	return Turn{Calls: []Call{{Name: name, Arguments: arguments}}, Usage: defaultUsage()}
}

// ToolCalls returns a turn that requests the given tool invocations in order
// and reports the default token usage.
func ToolCalls(calls ...Call) Turn {
	return Turn{Calls: calls, Usage: defaultUsage()}
}

// Request is one HTTP request captured by the fake provider.
type Request struct {
	// Method is the HTTP method of the request.
	Method string

	// Path is the request path, which selects the wire protocol.
	Path string

	// Header holds the request headers.
	Header http.Header

	// Body holds the complete request body.
	Body []byte
}

// FakeProvider is the fake model provider of the suite: an HTTP server that
// answers every request of the compiled binary with the next scripted turn and
// records the requests it receives, so tests can assert what the application
// sent over the wire.
//
// A FakeProvider is an http.Handler: it routes each request to the codec of the
// protocol its path belongs to, which lets a single server answer any of the
// supported protocols.
type FakeProvider struct {
	script []Turn
	server *httptest.Server

	mu       sync.Mutex
	requests []Request
	arrival  chan struct{}
}

// newFakeProvider starts the fake provider of one test with the given script
// and registers its shutdown.
func newFakeProvider(t *testing.T, script []Turn) *FakeProvider {
	t.Helper()

	provider := &FakeProvider{script: slices.Clone(script), arrival: make(chan struct{}, 1)}
	provider.server = httptest.NewServer(provider)
	t.Cleanup(provider.server.Close)
	return provider
}

// BaseURL returns the endpoint root of the fake provider, the value the
// generated configurations use for the providers that declare no base URL.
func (p *FakeProvider) BaseURL() string {
	return p.server.URL + "/v1"
}

// ServeHTTP answers one request with the next scripted turn, streaming the
// payloads of the protocol its path belongs to.
func (p *FakeProvider) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	body, err := io.ReadAll(r.Body)
	_ = r.Body.Close()
	if err != nil {
		http.Error(w, "fake provider: read request body: "+err.Error(), http.StatusBadRequest)
		return
	}

	codec, found := codecForPath(r.URL.Path)
	if !found {
		http.Error(w, "fake provider: unsupported provider path "+r.URL.Path, http.StatusNotFound)
		return
	}

	turn, sequence, scripted := p.record(r, body)
	if !scripted {
		http.Error(w, "fake provider: the script ran out of turns", http.StatusInternalServerError)
		return
	}

	if turn.Status != 0 {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(turn.Status)
		_, _ = io.WriteString(w, `{"error":{"message":"`+http.StatusText(turn.Status)+`"}}`)
		return
	}

	payloads, err := codec.payloads(turn, sequence, modelOf(body))
	if err != nil {
		http.Error(
			w,
			"fake provider: encode response: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}

	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-store")
	w.WriteHeader(http.StatusOK)

	flusher, _ := w.(http.Flusher)
	for _, payload := range payloads {
		if turn.ChunkDelay > 0 {
			time.Sleep(turn.ChunkDelay)
		}
		if r.Context().Err() != nil {
			return
		}
		if _, err := io.WriteString(w, "data: "+payload+"\n\n"); err != nil {
			return
		}
		if flusher != nil {
			flusher.Flush()
		}
	}
}

// record stores one received request and returns the next scripted turn
// together with its position in the request sequence.
func (p *FakeProvider) record(r *http.Request, body []byte) (Turn, int, bool) {
	p.mu.Lock()
	defer p.mu.Unlock()

	p.requests = append(p.requests, Request{
		Method: r.Method,
		Path:   r.URL.Path,
		Header: r.Header.Clone(),
		Body:   slices.Clone(body),
	})
	select {
	case p.arrival <- struct{}{}:
	default:
	}

	sequence := len(p.requests)
	if len(p.script) == 0 {
		return Turn{}, sequence, false
	}
	turn := p.script[0]
	p.script = p.script[1:]
	return turn, sequence, true
}

// Requests returns every request the provider received so far, in arrival
// order.
func (p *FakeProvider) Requests() []Request {
	p.mu.Lock()
	defer p.mu.Unlock()
	return slices.Clone(p.requests)
}

// LastRequest returns the most recent request the provider received, failing
// the test when it received none.
func (p *FakeProvider) LastRequest(t *testing.T) Request {
	t.Helper()

	requests := p.Requests()
	if len(requests) == 0 {
		t.Fatal("fake provider: no request was received")
	}
	return requests[len(requests)-1]
}

// WaitRequest blocks until the fake provider receives its next request, so a
// test can act while a run is in flight.
func (p *FakeProvider) WaitRequest(t *testing.T) {
	t.Helper()

	select {
	case <-p.arrival:
	case <-time.After(arrivalTimeout):
		t.Fatalf("fake provider: received no request within %s", arrivalTimeout)
	}
}

// codec is the codec of one wire protocol: it turns a scripted turn into the
// server-sent event payloads of a streamed response.
type codec interface {
	// payloads returns the payloads of one response, in order, ending with the
	// sentinel that closes the stream of the protocol.
	payloads(turn Turn, sequence int, model string) ([]string, error)
}

// codecForPath returns the codec of the protocol a provider path belongs to.
func codecForPath(path string) (codec, bool) {
	switch {
	case strings.HasSuffix(path, "/chat/completions"):
		return chatStream{}, true
	case strings.HasSuffix(path, "/messages"):
		return anthropicStream{}, true
	case strings.HasSuffix(path, "/responses"):
		return responsesStream{}, true
	default:
		return nil, false
	}
}

// modelOf returns the model identifier of a request body, empty when the body
// declares none.
func modelOf(body []byte) string {
	var envelope struct {
		Model string `json:"model"`
	}
	// A body the provider cannot decode is answered with an empty model, which
	// the assertions of the suite surface as a failed expectation.
	_ = json.Unmarshal(body, &envelope)
	return envelope.Model
}

// chunkText splits text into at most parts fragments of similar length, so a
// response can be streamed incrementally without a huge answer.
func chunkText(text string, parts int) []string {
	if text == "" {
		return nil
	}

	runes := []rune(text)
	switch {
	case parts <= 1:
		return []string{text}
	case parts >= len(runes):
		fragments := make([]string, 0, len(runes))
		for _, r := range runes {
			fragments = append(fragments, string(r))
		}
		return fragments
	}

	size := (len(runes) + parts - 1) / parts
	fragments := make([]string, 0, parts)
	for start := 0; start < len(runes); start += size {
		fragments = append(fragments, string(runes[start:min(start+size, len(runes))]))
	}
	return fragments
}

// argumentsOf returns the JSON arguments of a tool call, as the model would
// have emitted them.
func argumentsOf(call Call) (string, error) {
	if call.RawArguments != "" {
		return call.RawArguments, nil
	}
	encoded, err := json.Marshal(call.Arguments)
	if err != nil {
		return "", fmt.Errorf("fake provider: encode tool call arguments: %w", err)
	}
	return string(encoded), nil
}

// callID returns the identifier of a tool call, generating one when the test
// declared none.
func callID(call Call, sequence, index int) string {
	if call.ID != "" {
		return call.ID
	}
	return fmt.Sprintf("call_%d_%d", sequence, index+1)
}

// responseID builds the identifier of a scripted response from its protocol
// prefix and its position in the request sequence.
func responseID(prefix string, sequence int) string {
	return fmt.Sprintf("%s_%d", prefix, sequence)
}

// fragmentArguments cuts a tool argument payload into two fragments when the
// turn streams more than one, as real providers send the arguments
// incrementally.
func fragmentArguments(arguments string, parts int) []string {
	return chunkText(arguments, min(max(parts, 0), 2))
}
