// Command brew generates the Rienda Homebrew formulas.
//
// Given a released version, it downloads the release manifest, verifies that
// every platform archive the formulas need is present with its checksum, and
// writes the formula files into a Homebrew tap checkout: the moving formula
// for stable and pre-release versions, plus a pinned versioned formula for
// stable versions. The release workflow runs this command against the tap
// repository and publishes the result.
package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

// Permissions of the generated formulas.
//
// The release workflow generates them inside a container running as root and
// commits them from the host with the unprivileged user of the runner, so the
// formula directory and its files must stay readable by every user.
const (
	formulaDirMode  = 0o755
	formulaFileMode = 0o644
)

const (
	formulaDir       = "Formula/rienda"
	githubRepo       = "varavelio/rienda"
	manifestFileName = "manifest.json"
	projectDesc      = "Simple, declarative, multi-agent LLM harness"
	projectHome      = "https://github.com/varavelio/rienda"
)

type releaseArtifact struct {
	Name   string `json:"name"`
	SHA256 string `json:"sha256"`
}

type releaseManifest struct {
	Artifacts []releaseArtifact `json:"artifacts"`
}

// main runs the Homebrew formula generator and owns process exit behavior.
func main() {
	if err := run(context.Background(), fetchReleaseChecksums); err != nil {
		fmt.Fprintf(os.Stderr, "generate homebrew formulas: %s\n", err)
		os.Exit(1)
	}
}

// run generates the Homebrew formula files for one released version, with
// the artifact checksums resolved by fetchChecksums.
func run(
	ctx context.Context,
	fetchChecksums func(context.Context, string) (map[string]string, error),
) error {
	if len(os.Args) < 2 || len(os.Args) > 3 {
		return errors.New("usage: go run ./installers/brew vx.y.z [tap-root]")
	}

	version := normalizeVersion(os.Args[1])
	outputRoot := "."
	if len(os.Args) == 3 {
		outputRoot = os.Args[2]
	}

	hashes, err := fetchChecksums(ctx, version)
	if err != nil {
		return err
	}

	currentFile := "rienda.rb"
	if strings.Contains(version, "-") {
		currentFile = "rienda-next.rb"
	}
	if err := writeFormula(outputRoot, currentFile, version, hashes); err != nil {
		return err
	}

	// Only stable versions get a pinned versioned formula; pre-releases
	// are only reachable through the moving rienda-next formula.
	if strings.Contains(version, "-") {
		return nil
	}
	pinnedFile := "rienda@" + version + ".rb"

	return writeFormula(outputRoot, pinnedFile, version, hashes)
}

// writeFormula writes one Homebrew formula file.
//
//nolint:gosec // the tap root is selected by the operator running the release.
func writeFormula(outputRoot, fileName, version string, hashes map[string]string) error {
	content, err := generateFormula(fileName, version, hashes)
	if err != nil {
		return err
	}
	directory := filepath.Join(outputRoot, filepath.FromSlash(formulaDir))
	//nolint:gosec // the formulas are published, so they must be world-readable.
	if err := os.MkdirAll(directory, formulaDirMode); err != nil {
		return fmt.Errorf("create formula directory: %w", err)
	}
	path := filepath.Join(directory, fileName)
	//nolint:gosec // the formulas are published, so they must be world-readable.
	if err := os.WriteFile(path, []byte(content), formulaFileMode); err != nil {
		return fmt.Errorf("write %s: %w", fileName, err)
	}

	return nil
}

// generateFormula returns the Ruby formula content for one formula filename.
func generateFormula(fileName, version string, hashes map[string]string) (string, error) {
	required := []string{
		"rienda_darwin_arm64.tar.gz",
		"rienda_darwin_amd64.tar.gz",
		"rienda_linux_arm64.tar.gz",
		"rienda_linux_amd64.tar.gz",
	}
	for _, name := range required {
		if hashes[name] == "" {
			return "", fmt.Errorf("checksum for %s is missing", name)
		}
	}

	baseURL := releaseBaseURL(version)
	var builder strings.Builder
	builder.WriteString("# This file was generated by the Rienda release workflow. DO NOT EDIT.\n")
	fmt.Fprintf(&builder, "class %s < Formula\n", formulaClassName(fileName))
	fmt.Fprintf(&builder, "  desc %q\n", projectDesc)
	fmt.Fprintf(&builder, "  homepage %q\n", projectHome)
	builder.WriteString("  license \"MIT\"\n")
	fmt.Fprintf(&builder, "  version %q\n\n", version)
	builder.WriteString("  on_macos do\n")
	builder.WriteString("    if Hardware::CPU.arm?\n")
	fmt.Fprintf(&builder, "      url %q\n", baseURL+"/rienda_darwin_arm64.tar.gz")
	fmt.Fprintf(&builder, "      sha256 %q\n", hashes["rienda_darwin_arm64.tar.gz"])
	builder.WriteString("    else\n")
	fmt.Fprintf(&builder, "      url %q\n", baseURL+"/rienda_darwin_amd64.tar.gz")
	fmt.Fprintf(&builder, "      sha256 %q\n", hashes["rienda_darwin_amd64.tar.gz"])
	builder.WriteString("    end\n")
	builder.WriteString("  end\n\n")
	builder.WriteString("  on_linux do\n")
	builder.WriteString("    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?\n")
	fmt.Fprintf(&builder, "      url %q\n", baseURL+"/rienda_linux_arm64.tar.gz")
	fmt.Fprintf(&builder, "      sha256 %q\n", hashes["rienda_linux_arm64.tar.gz"])
	builder.WriteString("    else\n")
	fmt.Fprintf(&builder, "      url %q\n", baseURL+"/rienda_linux_amd64.tar.gz")
	fmt.Fprintf(&builder, "      sha256 %q\n", hashes["rienda_linux_amd64.tar.gz"])
	builder.WriteString("    end\n")
	builder.WriteString("  end\n\n")
	builder.WriteString("  def install\n")
	builder.WriteString("    bin.install \"rienda\"\n")
	builder.WriteString("  end\n\n")
	builder.WriteString("  test do\n")
	builder.WriteString("    system \"#{bin}/rienda\", \"--help\"\n")
	builder.WriteString("  end\n")
	builder.WriteString("end\n")

	return builder.String(), nil
}

// fetchReleaseChecksums downloads the release manifest for version and maps
// artifact names to their SHA-256 checksums.
func fetchReleaseChecksums(ctx context.Context, version string) (map[string]string, error) {
	return fetchManifest(ctx, manifestURL(version))
}

// fetchManifest downloads a manifest URL and maps artifact names to their
// SHA-256 checksums.
//
//nolint:gosec // the URL always points at the release of the project repository.
func fetchManifest(ctx context.Context, url string) (map[string]string, error) {
	request, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, fmt.Errorf("create manifest request: %w", err)
	}
	response, err := http.DefaultClient.Do(request)
	if err != nil {
		return nil, fmt.Errorf("download manifest: %w", err)
	}
	defer func() {
		_ = response.Body.Close()
	}()
	if response.StatusCode >= http.StatusBadRequest {
		return nil, fmt.Errorf("download manifest: %s", response.Status)
	}
	content, err := io.ReadAll(response.Body)
	if err != nil {
		return nil, fmt.Errorf("read manifest: %w", err)
	}

	return parseManifest(content)
}

// parseManifest parses manifest.json content into artifact checksums.
func parseManifest(content []byte) (map[string]string, error) {
	var manifest releaseManifest
	if err := json.Unmarshal(content, &manifest); err != nil {
		return nil, fmt.Errorf("parse manifest: %w", err)
	}

	checksums := map[string]string{}
	for _, artifact := range manifest.Artifacts {
		if artifact.Name == "" || artifact.SHA256 == "" {
			return nil, errors.New("invalid manifest artifact: name and sha256 are required")
		}
		checksums[artifact.Name] = artifact.SHA256
	}

	return checksums, nil
}

// manifestURL returns the release manifest URL for version.
func manifestURL(version string) string {
	return releaseBaseURL(version) + "/" + manifestFileName
}

// releaseBaseURL returns the GitHub release download URL for version.
func releaseBaseURL(version string) string {
	return "https://github.com/" + githubRepo + "/releases/download/v" + version
}

// normalizeVersion returns version without a leading v prefix.
func normalizeVersion(version string) string {
	version = strings.TrimSpace(strings.ToLower(version))

	return strings.TrimPrefix(version, "v")
}

// formulaClassName returns the Ruby class name for fileName.
func formulaClassName(fileName string) string {
	name := strings.TrimSuffix(fileName, ".rb")
	var builder strings.Builder
	capitalizeNext := true
	for _, char := range name {
		if isASCIIAlphanumeric(char) {
			if capitalizeNext {
				builder.WriteRune(unicode.ToUpper(char))
				capitalizeNext = false
				continue
			}
			builder.WriteRune(char)
			continue
		}
		if char == '@' {
			builder.WriteString("AT")
		}
		capitalizeNext = true
	}

	return builder.String()
}

// isASCIIAlphanumeric reports whether char is an ASCII letter or digit.
func isASCIIAlphanumeric(char rune) bool {
	return char >= 'a' && char <= 'z' || char >= 'A' && char <= 'Z' || char >= '0' && char <= '9'
}
