package llm

// StopReason explains why generation ended.
type StopReason string

const (
	// StopReasonEndTurn marks a natural completion of the response.
	StopReasonEndTurn StopReason = "end_turn"
	// StopReasonMaxTokens marks a response truncated by a token limit.
	StopReasonMaxTokens StopReason = "max_tokens"
	// StopReasonToolUse marks a response that requests tool calls.
	StopReasonToolUse StopReason = "tool_use"
	// StopReasonStopSequence marks a response ended by a stop sequence.
	StopReasonStopSequence StopReason = "stop_sequence"
	// StopReasonRefusal marks a response the model refused to produce.
	StopReasonRefusal StopReason = "refusal"
	// StopReasonContentFilter marks a response blocked by content filtering.
	StopReasonContentFilter StopReason = "content_filter"
	// StopReasonPaused marks a response paused by the provider mid-turn.
	StopReasonPaused StopReason = "paused"
)

// Usage reports token consumption of a single response.
type Usage struct {
	// InputTokens is the number of tokens in the request input.
	InputTokens int

	// OutputTokens is the number of tokens generated by the model.
	OutputTokens int

	// ReasoningTokens is the subset of OutputTokens spent on reasoning, when
	// the provider reports it.
	ReasoningTokens int

	// CacheReadTokens is the number of input tokens served from the provider
	// prompt cache, when the provider reports it.
	CacheReadTokens int

	// CacheWriteTokens is the number of input tokens written to the provider
	// prompt cache, when the provider reports it.
	CacheWriteTokens int
}

// Response is a provider-neutral generation result.
type Response struct {
	// ID is the provider-assigned identifier of the response.
	ID string

	// Model is the model that produced the response.
	Model string

	// Blocks is the ordered content generated by the model.
	Blocks []Block

	// StopReason explains why generation ended.
	StopReason StopReason

	// Usage reports the token consumption of the response.
	Usage Usage
}
