name: Run CI

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  ci:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Run command
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: task ci
